application: teambuzzapp
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /scripts
  static_dir: static/scripts

- url: /images
  static_dir: static/images

- url: /stylesheets
  static_dir: static/stylesheets

- url: /files
  static_dir: static/files
  mime_type: application/pdf

- url: /remoteapi.*
  script: google.appengine.ext.remote_api.handler.application
  login: admin

- url: /admin.*
  script: teambuzz.py
  login: admin

- url: /.*
  script: teambuzz.py

inbound_services:
- mail

libraries:
- name: django
  version: latest
- name: jinja2
  version: latest
